### ISSUE TITLE
Tab (file) navigation via Window menu

### ISSUE THREAD

**Issue by AcarBurak** [JuBan1/notepadqq#7]
I keep my editor window around 600px wide. So only 4-5 of my open files are visible on the tabs and file navigation via tabs are cumbersome and time consuming.

It would be a very fine convenience to be able to reach the open files (tabs) via the Window menu which currently only has one item.

**Comment by JuBan1** [comment]
Hi, thanks for the Issue but this is a subrepository for testing a specific piece of tech in Notepadqq. Could you open an Issue [here](https://github.com/notepadqq/notepadqq) instead?
